### ISSUE TITLE
Import error within package

### ISSUE THREAD

**Issue by XCanG** [secretum-inc/quo#37]
**Describe the bug**
I tried to execute examples from README.md, this one is for prompt, however I get an ImportError
```py
>>> completer = quo.completion.WordCompleter(['USA', 'UK', 'Canada', 'Kenya'])
>>> session = quo.Prompt(completer=completer)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python38\lib\site-packages\quo\shortcuts\prompt.py", line 452, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
  File "C:\Python\Python38\lib\site-packages\quo\shortcuts\prompt.py", line 703, in _create_application
    application: Suite[_T] = Suite(
  File "C:\Python\Python38\lib\site-packages\quo\suite\suite.py", line 280, in __init__
    self.output = output or session.output
  File "C:\Python\Python38\lib\site-packages\quo\suite\current.py", line 70, in output
    self._output = create_output()
  File "C:\Python\Python38\lib\site-packages\quo\output\defaults.py", line 59, in create_output
    from .console_emulator import ConEmu
  File "C:\Python\Python38\lib\site-packages\quo\output\console_emulator.py", line 8, in <module>
    from .win32 import Win32Output
  File "C:\Python\Python38\lib\site-packages\quo\output\win32.py", line 16, in <module>
    from quo.utils import get_cwidth
ImportError: cannot import name 'get_cwidth' from 'quo.utils' (C:\Python\Python38\lib\site-packages\quo\utils\__init__.py)
```

**To Reproduce**
1. Try to execute example
```py
import quo

completer = quo.completion.WordCompleter(['USA', 'UK', 'Canada', 'Kenya'])
session = quo.Prompt(completer=completer)
session.prompt('Which country are you from?: ')
```
2. See error

**Expected behavior**
Not throw an error.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Python version: 3.8
 - Quo version: 2021.07

**Comment by gerrishons** [comment]
Hello @XCanG the import error has been fixed. Thank you for submitting the bug.
Please update quo to the latest `version.`

> `pip install quo==2022.1.5`

**Comment by XCanG** [comment]
> Hello @XCanG the import error has been fixed. Thank you for submitting the bug. Please update quo to the latest `version.`
> 
> > `pip install quo==2022.1.5`

I've installed new version, but get new error now:
```py
>>> completer = quo.completion.WordCompleter(['USA', 'UK', 'Canada', 'Kenya'])
>>> session = quo.Prompt(completer=completer)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python38\lib\site-packages\quo\shortcuts\prompt.py", line 452, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
  File "C:\Python\Python38\lib\site-packages\quo\shortcuts\prompt.py", line 703, in _create_application
    application: Suite[_T] = Suite(
  File "C:\Python\Python38\lib\site-packages\quo\suite\suite.py", line 280, in __init__
    self.output = output or session.output
  File "C:\Python\Python38\lib\site-packages\quo\suite\current.py", line 70, in output
    self._output = create_output()
  File "C:\Python\Python38\lib\site-packages\quo\output\defaults.py", line 59, in create_output
    from .console_emulator import ConEmu
  File "C:\Python\Python38\lib\site-packages\quo\output\console_emulator.py", line 49, in <module>
    Output.register(ConEmuOutput)
NameError: name 'ConEmuOutput' is not defined
```

**Comment by gerrishons** [comment]
Hello were sorry for the inconvenience, we believe the bug has been fixed with this new update that rolled out today!

`pip install quo==2022.1.6`

Please feel free to submit any bugs you might encounter. We thank you for your contribution
